logging:
  level: INFO
  loggers:
    com.luke.force.the.use: DEBUG
    
server:
  rootPath: /api/*
  
database:
  driverClass: org.h2.Driver
  user: user
  password: user
  url: jdbc:h2:./target/imdb
  
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: create-drop
  
swagger:
  resourcePackage: com.luke.force.the.use.resources