INSERT INTO GENRES (ID, NAME) VALUES (1, 'Action');
INSERT INTO GENRES (ID, NAME) VALUES (2, 'Adventure');
INSERT INTO GENRES (ID, NAME) VALUES (3, 'Biography');
INSERT INTO GENRES (ID, NAME) VALUES (4, 'Comedy');
INSERT INTO GENRES (ID, NAME) VALUES (5, 'Crime');
INSERT INTO GENRES (ID, NAME) VALUES (6, 'Drama');
INSERT INTO GENRES (ID, NAME) VALUES (7, 'Family');
INSERT INTO GENRES (ID, NAME) VALUES (8, 'Fantasy');
INSERT INTO GENRES (ID, NAME) VALUES (9, 'History');
INSERT INTO GENRES (ID, NAME) VALUES (10, 'Horror');
INSERT INTO GENRES (ID, NAME) VALUES (11, 'Romance');
INSERT INTO GENRES (ID, NAME) VALUES (12, 'Sci-Fi');
INSERT INTO GENRES (ID, NAME) VALUES (13, 'Thriller');

INSERT INTO MOVIES (ID, NAME, STORYLINE, RELEASE_DATE, DURATION) VALUES (1, 'Venom', 'A failed reporter is bonded to an alien entity, one of many symbiotes who have invaded Earth. But the being takes a liking to Earth and decides to protect it.', '2018-10-05', 112);
INSERT INTO MOVIES (ID, NAME, STORYLINE, RELEASE_DATE, DURATION) VALUES (2, 'Captain Marvel', 'Carol Danvers becomes one of the universes most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.', '2019-03-08', 123);
INSERT INTO MOVIES (ID, NAME, STORYLINE, RELEASE_DATE, DURATION) VALUES (3, 'Captain America: The First Avenger', 'Steve Rogers, a rejected military soldier transforms into Captain America after taking a dose of a "Super-Soldier serum". But being Captain America comes at a price as he attempts to take down a war monger and a terrorist organization.', '2011-08-05', 124);

INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE_ID) VALUES (1, 1);
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE_ID) VALUES (1, 12);
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE_ID) VALUES (1, 13);
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE_ID) VALUES (2, 1);
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE_ID) VALUES (2, 2);
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE_ID) VALUES (2, 12);
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE_ID) VALUES (3, 1);
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE_ID) VALUES (3, 2);
INSERT INTO MOVIE_GENRE (MOVIE_ID, GENRE_ID) VALUES (3, 12);

INSERT INTO ACTORS (ID, NAME, SURNAME, BIRTH_DATE) VALUES (1, 'Brie', 'Larson', '1989-10-01');
INSERT INTO ACTORS (ID, NAME, SURNAME, BIRTH_DATE) VALUES (2, 'Samuel L.', 'Jackson', '1948-12-21');
INSERT INTO ACTORS (ID, NAME, SURNAME, BIRTH_DATE) VALUES (3, 'Chris', 'Evans', '1981-06-13');
INSERT INTO ACTORS (ID, NAME, SURNAME, BIRTH_DATE) VALUES (4, 'Tom', 'Hardy', '1977-09-15');

INSERT INTO MOVIE_ACTORS (MOVIE_ID, ACTOR_ID) VALUES (2, 1);
INSERT INTO MOVIE_ACTORS (MOVIE_ID, ACTOR_ID) VALUES (2, 2);
INSERT INTO MOVIE_ACTORS (MOVIE_ID, ACTOR_ID) VALUES (3, 3);
INSERT INTO MOVIE_ACTORS (MOVIE_ID, ACTOR_ID) VALUES (3, 2);
INSERT INTO MOVIE_ACTORS (MOVIE_ID, ACTOR_ID) VALUES (1, 4);
